/**
 * Dev-only generator (NOT run in CI): bundles `@tepegoz/reader`'s extractor into a committed TS string
 * so the main process can evaluate it inside a browsed page without shipping a module loader there.
 *
 *   pnpm --filter @tepegoz/desktop exec vite-node scripts/generate-reader-bundle.ts
 *
 * Committed output is the source of truth for `pnpm build`, exactly like the video-player bundle. The
 * generator exists so the injected copy cannot drift from the extractor the tests exercise — the two
 * ARE the same source, compiled twice.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const entry = resolve(here, '../../../packages/reader/src/inject-entry.ts');

const result = await build({
  entryPoints: [entry],
  bundle: true,
  write: false,
  format: 'iife',
  globalName: '__tepegozReader',
  platform: 'browser',
  target: 'es2022',
  minify: true,
});

const code = result.outputFiles[0]?.text ?? '';
if (code.length === 0) throw new Error('reader bundle came out empty');

// The trailing expression is what `executeJavaScript` resolves with. `void 0` guards the case where
// the IIFE somehow did not define the global — better an undefined result the caller rejects than a
// ReferenceError thrown into the page.
const source = `${code}\n(typeof __tepegozReader === 'object' ? __tepegozReader.extractFromPage() : null)`;

const out = resolve(here, '../src/main/reader/reader-bundle.ts');
writeFileSync(
  out,
  '// AUTO-GENERATED by scripts/generate-reader-bundle.ts — do not edit.\n' +
    '// Source: packages/reader/src/inject-entry.ts (bundled IIFE, evaluated inside a browsed page).\n' +
    '// Regenerate with: pnpm --filter @tepegoz/desktop exec vite-node scripts/generate-reader-bundle.ts\n' +
    `export const READER_EXTRACTOR_SOURCE = ${JSON.stringify(source)};\n`,
);
// eslint-disable-next-line no-console
console.log(`[generate-reader-bundle] ${out} (${source.length} bytes)`);
