/**
 * Dev-only generator (NOT run in CI): vendors the kui-player embed IIFE + its version into a committed
 * TS string constant so the packaged app is hermetic and never reaches across the WSL boundary. Re-run
 * this after rebuilding the player's `dist/embed.js`:
 *
 *   KUI_PLAYER_DIST=/path/to/kui-player pnpm --filter @tepegoz/desktop exec vite-node scripts/generate-video-player-bundle.ts
 *
 * The committed `video-player-embed-bundle.electron.ts` is the source of truth for `pnpm build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

const distRoot = process.env.KUI_PLAYER_DIST ?? '//wsl.localhost/Ubuntu/home/kuray/kui-player';
const bundlePath = resolve(distRoot, 'dist/embed.js');
const pkgPath = resolve(distRoot, 'package.json');

const bundle = readFileSync(bundlePath, 'utf8');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string };

const out = resolve(here, '../src/main/extensions/video-player-embed-bundle.electron.ts');
const banner =
  '// AUTO-GENERATED by scripts/generate-video-player-bundle.ts — do not edit.\n' +
  '// Source: @kuraykaraaslan/kui-player dist/embed.js (self-contained IIFE, Cast disabled).\n' +
  '// Regenerate with KUI_PLAYER_DIST=<kui-player> vite-node scripts/generate-video-player-bundle.ts\n';
const file =
  `${banner}` +
  `export const VIDEO_PLAYER_EMBED_JS = ${JSON.stringify(bundle)};\n` +
  `export const VIDEO_PLAYER_EMBED_VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(out, file);
// eslint-disable-next-line no-console
console.log(
  `[generate-video-player-bundle] ${out} (${bundle.length} bytes of JS, v${pkg.version})`,
);
