import { createHash } from 'node:crypto';
import { canonicalJson } from './canonical-json';

/**
 * Per-event hash chain over the Event Journal (Phase 7 NotaryService).
 *
 * The property this exists to prove: **if any event in a chain is altered, added, removed, or
 * reordered after the fact, the chain no longer verifies.** Each event's hash folds in the previous
 * event's hash, so changing event 3 changes its own hash, which changes what event 4 was chained
 * against, and the break propagates to the end of the chain — there is no way to edit one record
 * without either recomputing every hash after it (which the signed checkpoint then catches) or leaving
 * a visible break.
 *
 * What this module does NOT claim: it does not stop someone with access to the raw database from
 * editing a row and recomputing the chain from that point forward. That is what the signed checkpoint
 * is for (see `checkpoint.ts`) — a chain with no external anchor can always be regenerated by whoever
 * holds the private key that signs it, so the checkpoint is what makes a REPLAY RECEIPT portable
 * evidence rather than a self-consistent story.
 */

/** The hash chained-into the first event of a device's journal. Fixed and public, not a secret. */
export const GENESIS_HASH = '0'.repeat(64);

/** The minimal shape a chain needs from an event. A structural subset of `EventRecord` (shared-types),
 *  kept narrow so this module has no dependency on the persistence layer's row shape. */
export interface ChainableEvent {
  id: string;
  type: string;
  ts: number;
  actor: string;
  correlationId: string;
  payload: unknown;
  blobRef?: string | undefined;
  redacted: boolean;
}

export interface ChainedEvent extends ChainableEvent {
  prevHash: string;
  selfHash: string;
}

/** The one-way function: fold everything that identifies this event, plus its predecessor's hash, into
 *  64 hex characters. `payload`/`blobRef` are exactly what the Journal already redacts before storing —
 *  see the module doc's note on what a chain over redacted content does and does not prove. */
export function selfHashOf(event: ChainableEvent, prevHash: string): string {
  const canonical = canonicalJson({
    prevHash,
    id: event.id,
    type: event.type,
    ts: event.ts,
    actor: event.actor,
    correlationId: event.correlationId,
    payload: event.payload,
    blobRef: event.blobRef,
    redacted: event.redacted,
  });
  return createHash('sha256').update(canonical, 'utf8').digest('hex');
}

/**
 * Chain a sequence of events, in the order given.
 *
 * The caller supplies the order (normally journal `lsn` order) — this function trusts it rather than
 * re-sorting, so a caller cannot accidentally launder a reordering attack through a "helpful" sort that
 * silently accepts a tampered sequence as if it were original.
 */
export function chainEvents(
  events: readonly ChainableEvent[],
  genesis: string = GENESIS_HASH,
): ChainedEvent[] {
  const out: ChainedEvent[] = [];
  let prevHash = genesis;
  for (const event of events) {
    const selfHash = selfHashOf(event, prevHash);
    out.push({ ...event, prevHash, selfHash });
    prevHash = selfHash;
  }
  return out;
}

export type ChainVerdict =
  | { valid: true }
  | { valid: false; reason: 'empty' | 'broken_genesis' | 'broken_link' | 'hash_mismatch'; atIndex: number };

/**
 * Verify a previously-chained sequence.
 *
 * Recomputes every `selfHash` from its own fields and its recorded `prevHash`, and checks that each
 * `prevHash` actually equals the PRECEDING event's `selfHash` — the two checks catch different attacks.
 * A hash mismatch means this event's own recorded fields were altered. A broken link means the events
 * are intact individually but were reordered, had one removed, or had one inserted — the chain between
 * them is what breaks, not either event on its own.
 */
export function verifyChain(
  chained: readonly ChainedEvent[],
  genesis: string = GENESIS_HASH,
): ChainVerdict {
  if (chained.length === 0) return { valid: false, reason: 'empty', atIndex: -1 };
  let expectedPrev = genesis;
  for (let i = 0; i < chained.length; i++) {
    const event = chained[i];
    if (event === undefined) return { valid: false, reason: 'empty', atIndex: i };
    if (event.prevHash !== expectedPrev) {
      return { valid: false, reason: i === 0 ? 'broken_genesis' : 'broken_link', atIndex: i };
    }
    const recomputed = selfHashOf(event, event.prevHash);
    if (recomputed !== event.selfHash) {
      return { valid: false, reason: 'hash_mismatch', atIndex: i };
    }
    expectedPrev = event.selfHash;
  }
  return { valid: true };
}

/** The root hash of a chained sequence — the single value a checkpoint signs. */
export function chainRoot(chained: readonly ChainedEvent[]): string | null {
  const last = chained[chained.length - 1];
  return last === undefined ? null : last.selfHash;
}
